nome = input('Digite seu nome completo: ').strip()
pnome = nome.split()
print('Analisando seu nome... ')
print('Seu nome em maiúsculas é {}'.format(nome.upper()))
print('Seu nome em minúscula é {}'.format(nome.lower()))
print('Seu nome tem ao todo {} letras'.format(len(nome) - nome.count(' ')))
print('Seu primeiro nome é "{}" e ele tem {} letras'.format(pnome[0].capitalize(), len(pnome[0])))
